#!/usr/bin/env bash
#
# Copyright 2026 Max Brito
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# Installs the Flutter build, which is the one to use. The older Python
# implementation is still here as install-python.sh.
set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/globeswitcher"
APP_DIR="$DATA_DIR/app"
BIN_DIR="$HOME/.local/bin"
AUTOSTART_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/autostart"
DESKTOP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
BACKUP="$DATA_DIR/keybindings-backup.json"
BUNDLE="$SRC_DIR/flutter_app/build/linux/x64/release/bundle"

if [ -z "${DISPLAY:-}" ]; then
    echo "DISPLAY is not set. globeswitcher is an X11 program and cannot run" >&2
    echo "on a Wayland session." >&2
    exit 1
fi

# --- build -------------------------------------------------------------------

if [ ! -x "$BUNDLE/globeswitcher" ] || [ "${GLOBESWITCHER_REBUILD:-}" = "1" ]; then
    if ! command -v flutter >/dev/null; then
        echo "No build found at $BUNDLE and flutter is not on PATH." >&2
        echo "Install the Flutter SDK, or run ./install-python.sh for the" >&2
        echo "original Python version." >&2
        exit 1
    fi
    echo "Building (this takes a minute the first time)..."
    # This machine serialises heavy builds; use the lock when it is present.
    if [ -x "$HOME/bin/android-build-locked" ]; then
        (cd "$SRC_DIR/flutter_app" &&
            "$HOME/bin/android-build-locked" flutter build linux --release)
    else
        (cd "$SRC_DIR/flutter_app" && flutter build linux --release)
    fi
fi

# --- stop whatever is running ------------------------------------------------

pkill -f "globeswitcher.__main__" 2>/dev/null || true   # the Python daemon
pkill -f "$APP_DIR/globeswitcher" 2>/dev/null || true
sleep 1

# --- install -----------------------------------------------------------------

rm -rf "$APP_DIR"
mkdir -p "$APP_DIR" "$BIN_DIR" "$AUTOSTART_DIR" "$DESKTOP_DIR" "$DATA_DIR"
cp -r "$BUNDLE"/. "$APP_DIR/"

cat > "$BIN_DIR/globeswitcher" <<LAUNCHER
#!/usr/bin/env bash
# Generated by globeswitcher's install.sh
exec "$APP_DIR/globeswitcher" "\$@"
LAUNCHER
chmod 755 "$BIN_DIR/globeswitcher"

install -m 644 "$APP_DIR/data/flutter_assets/assets/tray_globe.png" \
    "$DATA_DIR/globeswitcher.png"

# --- take over Alt+Tab -------------------------------------------------------

# X11 lets only one client grab a given key, so whatever the desktop has bound
# to Alt+Tab has to let go of it first. Only GNOME can be handled here; the
# original values are saved so uninstall.sh can put them back.
if command -v gsettings >/dev/null &&
    gsettings list-schemas 2>/dev/null | grep -q '^org.gnome.desktop.wm.keybindings$'; then
    if [ ! -f "$BACKUP" ]; then
        python3 - "$BACKUP" <<'PYTHON'
import json, subprocess, sys

saved = {}
for key in ("switch-windows", "switch-windows-backward"):
    saved[key] = subprocess.run(
        ["gsettings", "get", "org.gnome.desktop.wm.keybindings", key],
        capture_output=True, text=True).stdout.strip()
with open(sys.argv[1], "w") as handle:
    json.dump(saved, handle, indent=2)
PYTHON
    fi
    gsettings set org.gnome.desktop.wm.keybindings switch-windows "[]"
    gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "[]"
    echo "Released GNOME's hold on Alt+Tab (saved to $BACKUP)."
else
    echo "Not a GNOME session: unbind Alt+Tab in your desktop's keyboard"
    echo "settings yourself, or globeswitcher will never see the key."
fi

# --- autostart and menu entry ------------------------------------------------

cat > "$AUTOSTART_DIR/globeswitcher.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=Globe Switcher
Comment=Rotating-globe Alt+Tab window switcher
Exec=$BIN_DIR/globeswitcher
Icon=$DATA_DIR/globeswitcher.png
Terminal=false
X-GNOME-Autostart-enabled=true
DESKTOP

cat > "$DESKTOP_DIR/globeswitcher.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=Globe Switcher
Comment=Settings for the rotating-globe window switcher
Exec=$BIN_DIR/globeswitcher
Icon=$DATA_DIR/globeswitcher.png
Terminal=false
Categories=Utility;Settings;
DESKTOP

setsid nohup "$BIN_DIR/globeswitcher" >/dev/null 2>&1 < /dev/null &
sleep 2

echo
echo "Installed and running. Press Alt+Tab."
echo "The globe in the system tray opens settings; it starts on login from"
echo "$AUTOSTART_DIR/globeswitcher.desktop"
