#!/usr/bin/env bash
#
# Copyright 2026 Max Brito
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/globeswitcher/app"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/globeswitcher"
BIN_DIR="$HOME/.local/bin"
AUTOSTART_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/autostart"
BACKUP="$DATA_DIR/keybindings-backup.json"

command -v python3 >/dev/null || { echo "python3 is required" >&2; exit 1; }
python3 -c 'import numpy, PIL' 2>/dev/null || {
    echo "missing Python modules. On Debian/Ubuntu:" >&2
    echo "  sudo apt install python3-numpy python3-pil" >&2
    exit 1
}
python3 -c 'import ctypes.util,sys; sys.exit(0 if ctypes.util.find_library("X11") else 1)' || {
    echo "libX11 not found; globeswitcher needs an X11 session." >&2
    exit 1
}
if [ -z "${DISPLAY:-}" ]; then
    echo "DISPLAY is not set. globeswitcher is an X11 program and cannot run" >&2
    echo "on a Wayland session." >&2
    exit 1
fi

# --- program -----------------------------------------------------------------

rm -rf "$LIB_DIR"
mkdir -p "$LIB_DIR/tools" "$BIN_DIR" "$AUTOSTART_DIR" "$DATA_DIR"
cp -r "$SRC_DIR/globeswitcher" "$LIB_DIR/globeswitcher"
install -m 755 "$SRC_DIR/tools/globe-texture" "$LIB_DIR/tools/globe-texture"

cat > "$BIN_DIR/globeswitcher" <<LAUNCHER
#!/usr/bin/env bash
# Generated by globeswitcher's install.sh
exec python3 -P -c 'import sys; sys.path.insert(0, "$LIB_DIR"); \
from globeswitcher.__main__ import main; main()' "\$@"
LAUNCHER
chmod 755 "$BIN_DIR/globeswitcher"

# --- first texture -----------------------------------------------------------

echo "Rendering the first world map..."
"$LIB_DIR/tools/globe-texture" >/dev/null

# --- take over Alt+Tab -------------------------------------------------------

# X11 lets only one client grab a given key, so whatever the desktop has bound
# to Alt+Tab has to let go of it first. Only GNOME can be handled automatically;
# the original values are saved so uninstall.sh can put them back.
if command -v gsettings >/dev/null && \
   gsettings list-schemas 2>/dev/null | grep -q '^org.gnome.desktop.wm.keybindings$'; then
    if [ ! -f "$BACKUP" ]; then
        python3 - "$BACKUP" <<'PYTHON'
import json, subprocess, sys

keys = ["switch-windows", "switch-windows-backward"]
saved = {}
for key in keys:
    saved[key] = subprocess.run(
        ["gsettings", "get", "org.gnome.desktop.wm.keybindings", key],
        capture_output=True, text=True).stdout.strip()
with open(sys.argv[1], "w") as handle:
    json.dump(saved, handle, indent=2)
PYTHON
    fi
    gsettings set org.gnome.desktop.wm.keybindings switch-windows "[]"
    gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "[]"
    echo "Released GNOME's hold on Alt+Tab (saved to $BACKUP)."
else
    echo "Not a GNOME session: unbind Alt+Tab in your desktop's keyboard"
    echo "settings yourself, or globeswitcher will never see the key."
fi

# --- autostart ---------------------------------------------------------------

cat > "$AUTOSTART_DIR/globeswitcher.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=Globe Switcher
Comment=Rotating-globe Alt+Tab window switcher
Exec=$BIN_DIR/globeswitcher
Terminal=false
X-GNOME-Autostart-enabled=true
DESKTOP

pkill -f "globeswitcher\.__main__" 2>/dev/null || true
nohup "$BIN_DIR/globeswitcher" >/dev/null 2>&1 &
sleep 1

echo
echo "Installed and running. Press Alt+Tab."
echo "It starts automatically on login from $AUTOSTART_DIR/globeswitcher.desktop"
